### ISSUE TITLE
ClientSession timeout

### ISSUE THREAD

**Issue by Midnighter** [aio-libs/aioftp#101]
Hi, I have a bit of confusion about the different timeouts in the `ClientSession`. The `Client` supports `socket_timeout` and `path_timeout`. My first few operations are these:

```py
    async with aioftp.ClientSession(host) as client:
        await client.change_directory(ftp_directory)
        info = await client.stat(filename)
```

These I would like to timeout relatively quickly. However, later in the script I'm downloading files of several hundred megabytes in size. Obviously, if the above did not timeout I would assume that the FTP server is running fine and I don't want too short timeouts to interrupt my downloads. Can you advise me on the best settings for this scenario? At the moment, the FTP server I connect to is unavailable and my script is just stuck forever.

```py
            async with client.download_stream(filename) as stream:
                async for block in stream.iter_by_block():
```

**Comment by pohmelie** [comment]
`socket_timeout` is timeout for reading operations. If there was no data from connection (command or data) for `socket_timeout` seconds, then exception will be raised. It's not very good implementation, since this timeouts should be separated. `path_timeout` is timeout only for local non-blocking path operations it does nothing for socket connection to server.  
You can use current best practise with asyncio: [async-timeout](https://pypi.org/project/async_timeout/). Which is a lib with context manager to timeout wrapped block.
Also, to resolve stuck you can use debug level logging and wireshark. Did you receive any block at all? Did you try download file from ftp with different tools?

**Comment by Midnighter** [comment]
> Did you try download file from ftp with different tools?

As I said above, the FTP server I'm trying to connect to is currently unavailable. I think, I would need to set a timeout for `async with aioftp.ClientSession(host) as client:`. I will take a look at async-timeout as you suggest. Thanks.
