### ISSUE TITLE
Why there's many commands not implemented?

### ISSUE THREAD

**Issue by fpemud** [aio-libs/aioftp#119]
When I connect aioftp server using firefox:
"502 'size' not implemented"                             (firefox aborts the connection after that)

When I connect aioftp server using filezilla:
502 'auth' not implemented
502 'feat' not implemented

Is there any todo-list or roadmap?

**Comment by pohmelie** [comment]
Because, as readme said, it is a two of three main project goals:
* Minimum usable core.
* Do not use deprecated or overridden commands and features (if possible).

You don't need `SIZE`, because you can do `MLST`. But, nothing wrong if someone will implement missed commands and make a pr. There is no plans to extend command set from my side right now. Also, as readme said: this subsets (client and server) are enough for 99% of tasks, but if you need something, then you can easily extend current set of commands.

**Comment by pohmelie** [comment]
More to say, firefox will end ftp support in couple of months.
