### ISSUE TITLE
client.download without logging in

### ISSUE THREAD

**Issue by SCP-028** [aio-libs/aioftp#65]
Hi, thanks for developing this package! I ran into a problem when trying to download files from [PDB](ftp://ftp.wwpdb.org/pub/pdb/data/structures/divided/pdb/), as it doesn't seem to require a login, and aioftp fails to download. 

My test code looks like this:
```python
import asyncio
import aioftp
import uvloop


async def download_file(session, url):
    url = url.lstrip("ftp://ftp.wwpdb.org")
    id = url[-11:-7]
    ID = id.upper()
    await session.download(url, f"{ID}.ent.gz")
    print(url)


async def unzip(sem, work_queue):
    while not work_queue.empty():
        queue_url = await work_queue.get()
        async with sem:
            async with aioftp.ClientSession("ftp.wwpdb.org") as session:
                await download_file(session, queue_url)
        

def download_queue(urls):
    loop = uvloop.new_event_loop()
    asyncio.set_event_loop(loop)
    q = asyncio.Queue()
    sem = asyncio.Semaphore(10)
    [q.put_nowait(url) for url in urls]
    tasks = [asyncio.ensure_future(unzip(sem, q)) for _ in range(len(urls))]
    loop.run_until_complete(asyncio.gather(*tasks))
    # Zero-sleep to allow underlying connections to close
    loop.run_until_complete(asyncio.sleep(0))
    loop.close()

if __name__ == "__main__":
    urls = [
        'ftp://ftp.wwpdb.org/pub/pdb/data/structures/divided/pdb/nf/pdb4nfn.ent.gz', 'ftp://ftp.wwpdb.org/pub/pdb/data/structures/divided/pdb/ny/pdb4nyj.ent.gz', 'ftp://ftp.wwpdb.org/pub/pdb/data/structures/divided/pdb/mn/pdb2mnz.ent.gz', 'ftp://ftp.wwpdb.org/pub/pdb/data/structures/divided/pdb/ra/pdb4ra4.ent.gz', 'ftp://ftp.wwpdb.org/pub/pdb/data/structures/divided/pdb/x5/pdb4x5w.ent.gz', 'ftp://ftp.wwpdb.org/pub/pdb/data/structures/divided/pdb/dm/pdb2dmq.ent.gz', 'ftp://ftp.wwpdb.org/pub/pdb/data/structures/divided/pdb/n7/pdb2n7r.ent.gz', 'ftp://ftp.wwpdb.org/pub/pdb/data/structures/divided/pdb/om/pdb2omv.ent.gz', 'ftp://ftp.wwpdb.org/pub/pdb/data/structures/divided/pdb/oy/pdb3oy8.ent.gz', 'ftp://ftp.wwpdb.org/pub/pdb/data/structures/divided/pdb/fe/pdb3fej.ent.gz', 'ftp://ftp.wwpdb.org/pub/pdb/data/structures/divided/pdb/hw/pdb2hw9.ent.gz']
    download_queue(urls)
```

The output:
```
Traceback (most recent call last):
  File "test.py", line 50, in <module>
    download_queue(urls)
  File "test.py", line 42, in download_queue
    loop.run_until_complete(asyncio.gather(*tasks))
  File "uvloop/loop.pyx", line 1364, in uvloop.loop.Loop.run_until_complete
  File "test.py", line 29, in unzip
    await download_file(session, queue_url)
  File "test.py", line 20, in download_file
    await session.download(url, f"{ID}.ent.gz")
  File "/home/yi/miniconda3/lib/python3.6/site-packages/aioftp/client.py", line 903, in download
    if await self.is_file(source):
  File "/home/yi/miniconda3/lib/python3.6/site-packages/aioftp/client.py", line 690, in is_file
    info = await self.stat(path)
  File "/home/yi/miniconda3/lib/python3.6/site-packages/aioftp/client.py", line 662, in stat
    code, info = await self.command("MLST " + str(path), "2xx")
  File "/home/yi/miniconda3/lib/python3.6/site-packages/aioftp/client.py", line 248, in command
    self.check_codes(expected_codes, code, info)
  File "/home/yi/miniconda3/lib/python3.6/site-packages/aioftp/client.py", line 214, in check_codes
    raise errors.StatusCodeError(expected_codes, received_code, info)
aioftp.errors.StatusCodeError: Waiting for ('2xx',) but got 550 [" Can't check for file existence"]
```

Thanks for your help!

**Comment by pohmelie** [comment]
You should turn logging on via `logging.basicConfig(level=logging.DEBUG)` and you will see, that the problem is in paths. Concrete, [`lstrip`](https://docs.python.org/3/library/stdtypes.html?highlight=lstrip#str.lstrip) is not what you expect.

Change `url = url.lstrip("ftp://ftp.wwpdb.org")` to `url = url[len("ftp://ftp.wwpdb.org"):]` and boom, files will be downloaded. But it looks like your code still do not do what you expect, anyway this is not relevant to `aioftp`.
<details>
  <summary>log</summary>
<pre>
INFO:aioftp.client:220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
INFO:aioftp.client:220-You are user number 2 of 500 allowed.
INFO:aioftp.client:220-Local time is now 03:00. Server port: 2421.
INFO:aioftp.client:220-Only anonymous FTP is allowed here
INFO:aioftp.client:220 You will be disconnected after 15 minutes of inactivity.
INFO:aioftp.client:USER anonymous
INFO:aioftp.client:220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
INFO:aioftp.client:220-You are user number 3 of 500 allowed.
INFO:aioftp.client:220-Local time is now 03:00. Server port: 2421.
INFO:aioftp.client:220-Only anonymous FTP is allowed here
INFO:aioftp.client:220 You will be disconnected after 15 minutes of inactivity.
INFO:aioftp.client:USER anonymous
INFO:aioftp.client:220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
INFO:aioftp.client:220-You are user number 4 of 500 allowed.
INFO:aioftp.client:220-Local time is now 03:00. Server port: 2421.
INFO:aioftp.client:220-Only anonymous FTP is allowed here
INFO:aioftp.client:220 You will be disconnected after 15 minutes of inactivity.
INFO:aioftp.client:USER anonymous
INFO:aioftp.client:220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
INFO:aioftp.client:220-You are user number 11 of 500 allowed.
INFO:aioftp.client:220-Local time is now 03:00. Server port: 2421.
INFO:aioftp.client:220-Only anonymous FTP is allowed here
INFO:aioftp.client:220 You will be disconnected after 15 minutes of inactivity.
INFO:aioftp.client:USER anonymous
INFO:aioftp.client:220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
INFO:aioftp.client:220-You are user number 10 of 500 allowed.
INFO:aioftp.client:220-Local time is now 03:00. Server port: 2421.
INFO:aioftp.client:220-Only anonymous FTP is allowed here
INFO:aioftp.client:220 You will be disconnected after 15 minutes of inactivity.
INFO:aioftp.client:USER anonymous
INFO:aioftp.client:220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
INFO:aioftp.client:220-You are user number 9 of 500 allowed.
INFO:aioftp.client:220-Local time is now 03:00. Server port: 2421.
INFO:aioftp.client:220-Only anonymous FTP is allowed here
INFO:aioftp.client:220 You will be disconnected after 15 minutes of inactivity.
INFO:aioftp.client:USER anonymous
INFO:aioftp.client:220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
INFO:aioftp.client:220-You are user number 8 of 500 allowed.
INFO:aioftp.client:220-Local time is now 03:00. Server port: 2421.
INFO:aioftp.client:220-Only anonymous FTP is allowed here
INFO:aioftp.client:220 You will be disconnected after 15 minutes of inactivity.
INFO:aioftp.client:USER anonymous
INFO:aioftp.client:220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
INFO:aioftp.client:220-You are user number 5 of 500 allowed.
INFO:aioftp.client:220-Local time is now 03:00. Server port: 2421.
INFO:aioftp.client:220-Only anonymous FTP is allowed here
INFO:aioftp.client:220 You will be disconnected after 15 minutes of inactivity.
INFO:aioftp.client:USER anonymous
INFO:aioftp.client:220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
INFO:aioftp.client:220-You are user number 6 of 500 allowed.
INFO:aioftp.client:220-Local time is now 03:00. Server port: 2421.
INFO:aioftp.client:220-Only anonymous FTP is allowed here
INFO:aioftp.client:220 You will be disconnected after 15 minutes of inactivity.
INFO:aioftp.client:USER anonymous
INFO:aioftp.client:220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
INFO:aioftp.client:220-You are user number 7 of 500 allowed.
INFO:aioftp.client:220-Local time is now 03:00. Server port: 2421.
INFO:aioftp.client:220-Only anonymous FTP is allowed here
INFO:aioftp.client:220 You will be disconnected after 15 minutes of inactivity.
INFO:aioftp.client:USER anonymous
INFO:aioftp.client:331 Any password will work
INFO:aioftp.client:PASS anon@
INFO:aioftp.client:331 Any password will work
INFO:aioftp.client:PASS anon@
INFO:aioftp.client:331 Any password will work
INFO:aioftp.client:PASS anon@
INFO:aioftp.client:331 Any password will work
INFO:aioftp.client:PASS anon@
INFO:aioftp.client:331 Any password will work
INFO:aioftp.client:PASS anon@
INFO:aioftp.client:331 Any password will work
INFO:aioftp.client:PASS anon@
INFO:aioftp.client:331 Any password will work
INFO:aioftp.client:PASS anon@
INFO:aioftp.client:331 Any password will work
INFO:aioftp.client:PASS anon@
INFO:aioftp.client:331 Any password will work
INFO:aioftp.client:PASS anon@
INFO:aioftp.client:331 Any password will work
INFO:aioftp.client:PASS anon@
INFO:aioftp.client:230 Any password will work
INFO:aioftp.client:MLST ub/pdb/data/structures/divided/pdb/ny/pdb4nyj.ent.gz
INFO:aioftp.client:230 Any password will work
INFO:aioftp.client:MLST ub/pdb/data/structures/divided/pdb/nf/pdb4nfn.ent.gz
INFO:aioftp.client:230 Any password will work
INFO:aioftp.client:MLST ub/pdb/data/structures/divided/pdb/oy/pdb3oy8.ent.gz
INFO:aioftp.client:230 Any password will work
INFO:aioftp.client:MLST ub/pdb/data/structures/divided/pdb/ra/pdb4ra4.ent.gz
INFO:aioftp.client:230 Any password will work
INFO:aioftp.client:MLST ub/pdb/data/structures/divided/pdb/fe/pdb3fej.ent.gz
INFO:aioftp.client:230 Any password will work
INFO:aioftp.client:MLST ub/pdb/data/structures/divided/pdb/x5/pdb4x5w.ent.gz
INFO:aioftp.client:230 Any password will work
INFO:aioftp.client:MLST ub/pdb/data/structures/divided/pdb/n7/pdb2n7r.ent.gz
INFO:aioftp.client:230 Any password will work
INFO:aioftp.client:MLST ub/pdb/data/structures/divided/pdb/mn/pdb2mnz.ent.gz
INFO:aioftp.client:230 Any password will work
INFO:aioftp.client:MLST ub/pdb/data/structures/divided/pdb/om/pdb2omv.ent.gz
INFO:aioftp.client:230 Any password will work
INFO:aioftp.client:MLST ub/pdb/data/structures/divided/pdb/dm/pdb2dmq.ent.gz
INFO:aioftp.client:550 Can't check for file existence
INFO:aioftp.client:QUIT
INFO:aioftp.client:550 Can't check for file existence
INFO:aioftp.client:QUIT
INFO:aioftp.client:550 Can't check for file existence
INFO:aioftp.client:QUIT
INFO:aioftp.client:550 Can't check for file existence
INFO:aioftp.client:QUIT
INFO:aioftp.client:550 Can't check for file existence
INFO:aioftp.client:QUIT
INFO:aioftp.client:550 Can't check for file existence
INFO:aioftp.client:QUIT
INFO:aioftp.client:550 Can't check for file existence
INFO:aioftp.client:QUIT
INFO:aioftp.client:550 Can't check for file existence
INFO:aioftp.client:QUIT
INFO:aioftp.client:550 Can't check for file existence
INFO:aioftp.client:QUIT
INFO:aioftp.client:550 Can't check for file existence
INFO:aioftp.client:QUIT
INFO:aioftp.client:221-Goodbye. You uploaded 0 and downloaded 0 kbytes.
INFO:aioftp.client:221 Logout.
INFO:aioftp.client:221-Goodbye. You uploaded 0 and downloaded 0 kbytes.
INFO:aioftp.client:221 Logout.
INFO:aioftp.client:221-Goodbye. You uploaded 0 and downloaded 0 kbytes.
INFO:aioftp.client:221 Logout.
Traceback (most recent call last):
  File "issue-65.py", line 39, in <module>
    download_queue(urls)
  File "issue-65.py", line 30, in download_queue
    loop.run_until_complete(asyncio.gather(*tasks))
  File "uvloop/loop.pyx", line 1203, in uvloop.loop.Loop.run_until_complete (uvloop/loop.c:25636)
  File "issue-65.py", line 20, in unzip
    await download_file(session, queue_url)
  File "issue-65.py", line 11, in download_file
    await session.download(url, f"{ID}.ent.gz")
  File "/home/broomrider/pro/aioftp/aioftp/client.py", line 903, in download
    if await self.is_file(source):
  File "/home/broomrider/pro/aioftp/aioftp/client.py", line 690, in is_file
    info = await self.stat(path)
  File "/home/broomrider/pro/aioftp/aioftp/client.py", line 662, in stat
    code, info = await self.command("MLST " + str(path), "2xx")
  File "/home/broomrider/pro/aioftp/aioftp/client.py", line 248, in command
    self.check_codes(expected_codes, code, info)
  File "/home/broomrider/pro/aioftp/aioftp/client.py", line 214, in check_codes
    raise errors.StatusCodeError(expected_codes, received_code, info)
aioftp.errors.StatusCodeError: Waiting for ('2xx',) but got 550 [" Can't check for file existence"]
</pre>
</details>

**Comment by SCP-028** [comment]
@pohmelie Thanks a lot! It's working on my computer now.
